import = ["~/.config/alacritty/tokyo-night.toml"]

[env]
TERM = "alacritty"

[font]
size = 20.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[window]
dynamic_padding = true
startup_mode = "Maximized"
